In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [1]:
import cv2

# IMAGE READING

In [2]:
img=cv2.imread("download.jpg")

In [3]:
img

array([[[ 46,  31,   0],
        [ 46,  31,   0],
        [ 46,  31,   0],
        ...,
        [138,  93,  49],
        [138,  93,  49],
        [138,  93,  49]],

       [[ 47,  32,   0],
        [ 46,  31,   0],
        [ 46,  31,   0],
        ...,
        [138,  93,  49],
        [138,  93,  49],
        [138,  93,  49]],

       [[ 48,  33,   0],
        [ 47,  32,   0],
        [ 47,  32,   0],
        ...,
        [138,  93,  49],
        [138,  93,  49],
        [138,  93,  49]],

       ...,

       [[108,  81,  71],
        [108,  81,  71],
        [106,  81,  71],
        ...,
        [191, 154, 120],
        [191, 154, 120],
        [191, 154, 120]],

       [[106,  80,  68],
        [106,  80,  68],
        [106,  80,  68],
        ...,
        [189, 152, 118],
        [189, 152, 118],
        [189, 152, 118]],

       [[105,  79,  65],
        [105,  79,  65],
        [105,  79,  67],
        ...,
        [185, 148, 114],
        [185, 148, 114],
        [185, 148, 114]]

In [5]:
grey=cv2.imread("download.jpg",0)

In [6]:
grey

array([[ 23,  23,  23, ...,  85,  85,  85],
       [ 24,  23,  23, ...,  85,  85,  85],
       [ 25,  24,  24, ...,  85,  85,  85],
       ...,
       [ 81,  81,  81, ..., 148, 148, 148],
       [ 79,  79,  79, ..., 146, 146, 146],
       [ 78,  78,  78, ..., 142, 142, 142]], dtype=uint8)

In [ ]:
cv2.imshow("colour image",img)
cv2.imshow("greyscale image",grey)
cv2.waitKey(0)
cv2.destroyAllWindows()



## IMAGE WRITING

In [8]:
cv2.imwrite('C:/Users/admin/minions.jpg',img)

True

In [4]:
import numpy as nump

# IMAGE SHAPE

In [5]:
shape=img.shape

In [6]:
print(shape)

(168, 300, 3)


# IMAGE SIZE

In [7]:
size=img.size

In [8]:
print(size)

151200


# VALUE OF PIXEL

In [9]:
pixel=img[123,299]

In [10]:
print(pixel)

[199 156  99]


# colour splitting

In [15]:
b,g,r=cv2.split(img)
cv2.imshow("b",b)
cv2.waitKey(0)
cv2.imshow("g",g)
cv2.waitKey(0)
cv2.imshow("r",r)
cv2.waitKey(0)

-1

In [13]:
print(b,g,r)

[[ 46  46  46 ... 138 138 138]
 [ 47  46  46 ... 138 138 138]
 [ 48  47  47 ... 138 138 138]
 ...
 [108 108 106 ... 191 191 191]
 [106 106 106 ... 189 189 189]
 [105 105 105 ... 185 185 185]] [[ 31  31  31 ...  93  93  93]
 [ 32  31  31 ...  93  93  93]
 [ 33  32  32 ...  93  93  93]
 ...
 [ 81  81  81 ... 154 154 154]
 [ 80  80  80 ... 152 152 152]
 [ 79  79  79 ... 148 148 148]] [[  0   0   0 ...  49  49  49]
 [  0   0   0 ...  49  49  49]
 [  0   0   0 ...  49  49  49]
 ...
 [ 71  71  71 ... 120 120 120]
 [ 68  68  68 ... 118 118 118]
 [ 65  65  67 ... 114 114 114]]
